# Generated by Django 4.1.1 on 2022-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoty',
            new_name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='article_imgs'),
        ),
    ]
