# Generated by Django 4.1.1 on 2022-10-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_rename_categoty_post_category_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='Autor', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(db_column='Categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(db_column='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(db_column='Capa', default='default_cover.jpg', upload_to='article_imgs'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(db_column='Data_de_Postagem', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='resume',
            field=models.TextField(db_column='Resumo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_column='Título', max_length=100),
        ),
    ]
