# Generated by Django 4.1.1 on 2022-10-28 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='capa',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='conteúdo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='resume',
            new_name='resumo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='título',
        ),
    ]
