# Generated by Django 4.1.1 on 2022-11-07 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_rename_author_post_autor_rename_cover_post_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='capa',
            field=models.ImageField(default='default_cover.jpg', upload_to='article_imgs', verbose_name='capa'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteúdo',
            field=models.TextField(verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=models.TextField(verbose_name='resumo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='título',
            field=models.CharField(max_length=100, verbose_name='título'),
        ),
    ]
